---
- hosts: all
  become: true

  pre_tasks:
    - name: check host
      shell: |
        hostname
      register: out
    - name: show host
      debug:
        msg: "{{ out.stdout }}"

  tasks:
    - name: "install docker"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes
    - name: install apt-key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: install docker apt-repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
    
    - name:
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
#    - name: Install doker-compose
#      pip:
#        name: doker-compose

    - name: enable docker
      shell: |
        
        usermod -aG docker $USER
        systemctl enable docker
      args:
        executable: /bin/bash
         
