---
- hosts: all
  become: true

  pre_tasks:
    - name: check host
      shell: |
        hostname
      register: out
    - name: show host
      debug:
        msg: "{{ out.stdout }}"

  tasks:
    - name: "install docker"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes
    - name: install apt-key for docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: install docker apt-repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
    
    - name:
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
#    - name: Install doker-compose
#      pip:
#        name: doker-compose

    - name: enable docker
      shell: |
        
        usermod -aG docker $USER
        systemctl enable docker
      args:
        executable: /bin/bash
    
    - name: add docker network
      shell: "docker network create wordpress-network"
      args:
        executable: /bin/bash
    
    - name: Create a directory if it does not exist
      file:
        path: /data/wordpress
        state: directory
        owner: user
        group: user
        mode: '0755'
    - name: Copy file with owner and permissions
      copy:
        src: /src
        dest: /date/wordpress
        owner: user
        group: user
        mode: '0755'
   
    - name: add docker network
      shell: |
          docker volume create --name mariadb_data
          docker run -d --name mariadb \
          --env ALLOW_EMPTY_PASSWORD=yes \
          --env MARIADB_USER=bn_wordpress \
          --env MARIADB_DATABASE=bitnami_wordpress \
          --network wordpress-network \
          --volume mariadb_data:/bitnami/mariadb \
          bitnami/mariadb:latest
      args:
        executable: /bin/bash
    
    - name: add docker network
      shell: |
          docker volume create --name wordpress_data
          docker run -d --name wordpress \
          -p 8080:8080 -p 8443:8443 \
          -e ALLOW_EMPTY_PASSWORD=yes \
          -e WORDPRESS_DATABASE_USER=bn_wordpress \
          -e WORDPRESS_DATABASE_NAME=bitnami_wordpress \
          --network wordpress-network \
          --volume wordpress_data:/bitnami/wordpress \
          bitnami/wordpress:latest
      args:
        executable: /bin/bash