---
- hosts: all
  become: true

  pre_tasks:
    - name: check host
      shell: |
        hostname
      register: out
    - name: show host
      debug:
        msg: "{{ out.stdout }}"

    - name: test run docker
      shell: |
          systemctl is-active docker
      args:
        executable: /bin/bash
      register: output

    - name: install
        include_tasks: install_docker.yaml 
      when: output == inactive

    - name: add docker network
      shell: "docker network create wordpress-network"
      args:
        executable: /bin/bash



    - name: rollback and backup user data
        include_tasks: rollback.yaml        


    - name: Create a directory wordpress
      file:
        path: /data/wordpress
        state: directory
        owner: user
        group: user
        mode: '0755'
    - name: Create a directory mariadb
      file:
        path: /data/mariadb
        state: directory
        owner: user
        group: user
        mode: '0755'
    - name: Create a directory backup
      file:
        path: /data/backup
        state: directory
        owner: user
        group: user
        mode: '0755'

    - name: docker run mariadb
      shell: |
          docker run -d --name mariadb \
          --env ALLOW_EMPTY_PASSWORD=yes \
          --env MARIADB_USER=bn_wordpress \
          --env MARIADB_DATABASE=wordpress \
          --network wordpress-network \
          --volume mariadb_data:/data/mariadb \
          bitnami/mariadb:latest
      args:
        executable: /bin/bash
    
    - name: docker run wordpress 
      shell: |
          docker run -d --name wordpress \
          -p 8080:8080 -p 8443:8443 \
          -e ALLOW_EMPTY_PASSWORD=yes \
          -e WORDPRESS_DATABASE_USER=bn_wordpress \
          -e WORDPRESS_DATABASE_NAME=wordpress \
          --network wordpress-network \
          --volume wordpress_data:/data/wordpress \
          bitnami/wordpress:latest
      args:
        executable: /bin/bash